/* tslint:disable */
/* eslint-disable */
/**
 * Svatební hra
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosRequestConfig } from "axios";
import globalAxios from "axios";
import { ConfigurationParameters as SDKConfiguration, defaultConfigurationParameters } from "./configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
	DUMMY_BASE_URL,
	assertParamExists,
	serializeDataIfNeeded,
	setBasicAuthToObject,
	setSearchParams,
	toPathString,
} from "./common";
// @ts-ignore
import { BaseAPI, RequiredError } from "./base";

export type { ConfigurationParameters as SDKConfiguration } from "./configuration";

export class SDK {
	AdminApi: SDK.AdminApi;
	NotificationsApi: SDK.NotificationsApi;
	RootApi: SDK.RootApi;
	SubscriptionsApi: SDK.SubscriptionsApi;

	constructor(configurationParams: SDKConfiguration, axios?: AxiosInstance) {
		const configuration = Object.assign({}, defaultConfigurationParameters, configurationParams);

		if (!axios) axios = globalAxios.create();

		this.AdminApi = new SDK.AdminApi(configuration, axios!);
		this.NotificationsApi = new SDK.NotificationsApi(configuration, axios!);
		this.RootApi = new SDK.RootApi(configuration, axios!);
		this.SubscriptionsApi = new SDK.SubscriptionsApi(configuration, axios!);
	}
}

export namespace SDK {
	/**
	 *
	 * @export
	 * @interface ListNotificationsResponseDto
	 */
	export interface ListNotificationsResponseDto {
		/**
		 *
		 * @type {string}
		 * @memberof ListNotificationsResponseDto
		 */
		id: string;
		/**
		 *
		 * @type {string}
		 * @memberof ListNotificationsResponseDto
		 */
		message?: string;
		/**
		 *
		 * @type {string}
		 * @memberof ListNotificationsResponseDto
		 */
		createdAt?: string;
		/**
		 *
		 * @type {boolean}
		 * @memberof ListNotificationsResponseDto
		 */
		test?: boolean;
		/**
		 *
		 * @type {string}
		 * @memberof ListNotificationsResponseDto
		 */
		buttonTitle?: string;
		/**
		 *
		 * @type {string}
		 * @memberof ListNotificationsResponseDto
		 */
		buttonLink?: string;
	}

	/**
	 *
	 * @export
	 * @interface PushSubscriptionDto
	 */
	export interface PushSubscriptionDto {
		/**
		 *
		 * @type {string}
		 * @memberof PushSubscriptionDto
		 */
		endpoint: string;
		/**
		 *
		 * @type {number}
		 * @memberof PushSubscriptionDto
		 */
		expirationTime?: number | null;
		/**
		 *
		 * @type {PushSubscriptionDtoKeys}
		 * @memberof PushSubscriptionDto
		 */
		keys: PushSubscriptionDtoKeys;
	}

	/**
	 *
	 * @export
	 * @interface PushSubscriptionDtoKeys
	 */
	export interface PushSubscriptionDtoKeys {
		/**
		 *
		 * @type {string}
		 * @memberof PushSubscriptionDtoKeys
		 */
		p256dh: string;
		/**
		 *
		 * @type {string}
		 * @memberof PushSubscriptionDtoKeys
		 */
		auth: string;
	}

	/**
	 *
	 * @export
	 * @interface SendNotificationBodyDto
	 */
	export interface SendNotificationBodyDto {
		/**
		 *
		 * @type {string}
		 * @memberof SendNotificationBodyDto
		 */
		message: string;
		/**
		 *
		 * @type {string}
		 * @memberof SendNotificationBodyDto
		 */
		buttonTitle?: string;
		/**
		 *
		 * @type {string}
		 * @memberof SendNotificationBodyDto
		 */
		buttonLink?: string;
		/**
		 *
		 * @type {string}
		 * @memberof SendNotificationBodyDto
		 */
		test?: SendNotificationBodyDtoTestEnum;
	}

	export const SendNotificationBodyDtoTestEnum = {
		True: "true",
		False: "false",
	} as const;

	export type SendNotificationBodyDtoTestEnum =
		(typeof SendNotificationBodyDtoTestEnum)[keyof typeof SendNotificationBodyDtoTestEnum];

	/**
	 *
	 * @export
	 * @interface SendTestNotificationBodyDto
	 */
	export interface SendTestNotificationBodyDto {
		/**
		 *
		 * @type {object}
		 * @memberof SendTestNotificationBodyDto
		 */
		subscription: object;
		/**
		 *
		 * @type {string}
		 * @memberof SendTestNotificationBodyDto
		 */
		message: string;
	}

	/**
	 *
	 * @export
	 * @interface SubscriptionResponseDto
	 */
	export interface SubscriptionResponseDto {
		/**
		 *
		 * @type {string}
		 * @memberof SubscriptionResponseDto
		 */
		id: string;
		/**
		 *
		 * @type {string}
		 * @memberof SubscriptionResponseDto
		 */
		endpoint?: string;
		/**
		 *
		 * @type {string}
		 * @memberof SubscriptionResponseDto
		 */
		rsvpId?: string;
	}

	/**
	 * AdminApi - object-oriented interface
	 * @export
	 * @class AdminApi
	 * @extends {BaseAPI}
	 */
	export class AdminApi extends BaseAPI {
		constructor(
			protected override configuration: SDKConfiguration,
			protected override axios: AxiosInstance = globalAxios,
		) {
			super(configuration, configuration.basePath, axios);
		}

		/**
         * 
    
         * @param {AxiosRequestConfig} [options] Override http request option.
         * @throws {RequiredError}
         * @memberof AdminApi
         */

		public async refresh(options: AxiosRequestConfig = {}) {
			const localVarPath = `/api/admin/refresh`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const requestUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (this.configuration) {
				baseOptions = this.configuration.baseOptions;
			}

			const axiosRequestConfig: AxiosRequestConfig = { method: "GET", ...baseOptions, ...options };
			const requestHeaderParameter = {} as any;
			const requestQueryParameter = {} as any;

			// authentication basic-auth required
			// http basic authentication required
			setBasicAuthToObject(axiosRequestConfig, this.configuration);

			setSearchParams(requestUrlObj, requestQueryParameter);
			let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
			axiosRequestConfig.headers = { ...requestHeaderParameter, ...headersFromBaseOptions, ...options.headers };

			axiosRequestConfig["url"] = toPathString(requestUrlObj);
			axiosRequestConfig["baseURL"] = this.configuration.basePath;

			return this.axios.request<void>(axiosRequestConfig);
		}
	}

	/**
	 * Query parameters for listNotifications operation in NotificationsApi.
	 * @export
	 * @interface NotificationsApiListNotificationsQueryParams
	 */
	export interface NotificationsApiListNotificationsQueryParams {
		//includeTest
		/**
		 *
		 * @type {boolean}
		 * @memberof NotificationsApiListNotifications
		 */
		includeTest?: boolean;
	}

	/**
	 * NotificationsApi - object-oriented interface
	 * @export
	 * @class NotificationsApi
	 * @extends {BaseAPI}
	 */
	export class NotificationsApi extends BaseAPI {
		constructor(
			protected override configuration: SDKConfiguration,
			protected override axios: AxiosInstance = globalAxios,
		) {
			super(configuration, configuration.basePath, axios);
		}

		/**
         * 
    
         * @param {NotificationsApiListNotificationsQueryParams} queryParams Query parameters.
         * @param {AxiosRequestConfig} [options] Override http request option.
         * @throws {RequiredError}
         * @memberof NotificationsApi
         */

		public async listNotifications(
			queryParams: NotificationsApiListNotificationsQueryParams = {},
			options: AxiosRequestConfig = {},
		) {
			const localVarPath = `/api/notifications`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const requestUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (this.configuration) {
				baseOptions = this.configuration.baseOptions;
			}

			const axiosRequestConfig: AxiosRequestConfig = { method: "GET", ...baseOptions, ...options };
			const requestHeaderParameter = {} as any;
			const requestQueryParameter = {} as any;

			if (queryParams.includeTest !== undefined) {
				requestQueryParameter["includeTest"] = queryParams.includeTest;
			}

			setSearchParams(requestUrlObj, requestQueryParameter);
			let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
			axiosRequestConfig.headers = { ...requestHeaderParameter, ...headersFromBaseOptions, ...options.headers };

			axiosRequestConfig["url"] = toPathString(requestUrlObj);
			axiosRequestConfig["baseURL"] = this.configuration.basePath;

			return this.axios.request<Array<ListNotificationsResponseDto>>(axiosRequestConfig);
		}

		/**
         * 
    
         * @param {AxiosRequestConfig} [options] Override http request option.
         * @throws {RequiredError}
         * @memberof NotificationsApi
         */

		public async sendNotification(body: SendNotificationBodyDto, options: AxiosRequestConfig = {}) {
			// verify required parameter 'sendNotificationBodyDto' is not null or undefined
			assertParamExists("sendNotification", "sendNotificationBodyDto", body);

			const localVarPath = `/api/notifications`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const requestUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (this.configuration) {
				baseOptions = this.configuration.baseOptions;
			}

			const axiosRequestConfig: AxiosRequestConfig = { method: "POST", ...baseOptions, ...options };
			const requestHeaderParameter = {} as any;
			const requestQueryParameter = {} as any;

			// authentication basic-auth required
			// http basic authentication required
			setBasicAuthToObject(axiosRequestConfig, this.configuration);

			requestHeaderParameter["Content-Type"] = "application/json";

			setSearchParams(requestUrlObj, requestQueryParameter);
			let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
			axiosRequestConfig.headers = { ...requestHeaderParameter, ...headersFromBaseOptions, ...options.headers };
			axiosRequestConfig.data = serializeDataIfNeeded(body, axiosRequestConfig, this.configuration);

			axiosRequestConfig["url"] = toPathString(requestUrlObj);
			axiosRequestConfig["baseURL"] = this.configuration.basePath;

			return this.axios.request<void>(axiosRequestConfig);
		}

		/**
         * 
    
         * @param {AxiosRequestConfig} [options] Override http request option.
         * @throws {RequiredError}
         * @memberof NotificationsApi
         */

		public async sendTestNotification(body: SendTestNotificationBodyDto, options: AxiosRequestConfig = {}) {
			// verify required parameter 'sendTestNotificationBodyDto' is not null or undefined
			assertParamExists("sendTestNotification", "sendTestNotificationBodyDto", body);

			const localVarPath = `/api/notifications/test`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const requestUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (this.configuration) {
				baseOptions = this.configuration.baseOptions;
			}

			const axiosRequestConfig: AxiosRequestConfig = { method: "POST", ...baseOptions, ...options };
			const requestHeaderParameter = {} as any;
			const requestQueryParameter = {} as any;

			requestHeaderParameter["Content-Type"] = "application/json";

			setSearchParams(requestUrlObj, requestQueryParameter);
			let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
			axiosRequestConfig.headers = { ...requestHeaderParameter, ...headersFromBaseOptions, ...options.headers };
			axiosRequestConfig.data = serializeDataIfNeeded(body, axiosRequestConfig, this.configuration);

			axiosRequestConfig["url"] = toPathString(requestUrlObj);
			axiosRequestConfig["baseURL"] = this.configuration.basePath;

			return this.axios.request<void>(axiosRequestConfig);
		}
	}

	/**
	 * RootApi - object-oriented interface
	 * @export
	 * @class RootApi
	 * @extends {BaseAPI}
	 */
	export class RootApi extends BaseAPI {
		constructor(
			protected override configuration: SDKConfiguration,
			protected override axios: AxiosInstance = globalAxios,
		) {
			super(configuration, configuration.basePath, axios);
		}

		/**
         * 
         * @summary The OpenAPI document in JSON
    
         * @param {AxiosRequestConfig} [options] Override http request option.
         * @throws {RequiredError}
         * @memberof RootApi
         */

		public async getOpenAPIJSON(options: AxiosRequestConfig = {}) {
			const localVarPath = `/api-json`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const requestUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (this.configuration) {
				baseOptions = this.configuration.baseOptions;
			}

			const axiosRequestConfig: AxiosRequestConfig = { method: "GET", ...baseOptions, ...options };
			const requestHeaderParameter = {} as any;
			const requestQueryParameter = {} as any;

			setSearchParams(requestUrlObj, requestQueryParameter);
			let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
			axiosRequestConfig.headers = { ...requestHeaderParameter, ...headersFromBaseOptions, ...options.headers };

			axiosRequestConfig["url"] = toPathString(requestUrlObj);
			axiosRequestConfig["baseURL"] = this.configuration.basePath;

			return this.axios.request<string>(axiosRequestConfig);
		}

		/**
         * 
         * @summary The OpenAPI document in YAML
    
         * @param {AxiosRequestConfig} [options] Override http request option.
         * @throws {RequiredError}
         * @memberof RootApi
         */

		public async getOpenAPIYAML(options: AxiosRequestConfig = {}) {
			const localVarPath = `/api-yaml`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const requestUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (this.configuration) {
				baseOptions = this.configuration.baseOptions;
			}

			const axiosRequestConfig: AxiosRequestConfig = { method: "GET", ...baseOptions, ...options };
			const requestHeaderParameter = {} as any;
			const requestQueryParameter = {} as any;

			setSearchParams(requestUrlObj, requestQueryParameter);
			let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
			axiosRequestConfig.headers = { ...requestHeaderParameter, ...headersFromBaseOptions, ...options.headers };

			axiosRequestConfig["url"] = toPathString(requestUrlObj);
			axiosRequestConfig["baseURL"] = this.configuration.basePath;

			return this.axios.request<string>(axiosRequestConfig);
		}

		/**
         * 
         * @summary This SwaggerUI page
    
         * @param {AxiosRequestConfig} [options] Override http request option.
         * @throws {RequiredError}
         * @memberof RootApi
         */

		public async viewSwaggerUI(options: AxiosRequestConfig = {}) {
			const localVarPath = `/api`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const requestUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (this.configuration) {
				baseOptions = this.configuration.baseOptions;
			}

			const axiosRequestConfig: AxiosRequestConfig = { method: "GET", ...baseOptions, ...options };
			const requestHeaderParameter = {} as any;
			const requestQueryParameter = {} as any;

			setSearchParams(requestUrlObj, requestQueryParameter);
			let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
			axiosRequestConfig.headers = { ...requestHeaderParameter, ...headersFromBaseOptions, ...options.headers };

			axiosRequestConfig["url"] = toPathString(requestUrlObj);
			axiosRequestConfig["baseURL"] = this.configuration.basePath;

			return this.axios.request<string>(axiosRequestConfig);
		}
	}

	/**
	 * SubscriptionsApi - object-oriented interface
	 * @export
	 * @class SubscriptionsApi
	 * @extends {BaseAPI}
	 */
	export class SubscriptionsApi extends BaseAPI {
		constructor(
			protected override configuration: SDKConfiguration,
			protected override axios: AxiosInstance = globalAxios,
		) {
			super(configuration, configuration.basePath, axios);
		}

		/**
         * 
    
         * @param {AxiosRequestConfig} [options] Override http request option.
         * @throws {RequiredError}
         * @memberof SubscriptionsApi
         */

		public async saveSubscription(body: PushSubscriptionDto, options: AxiosRequestConfig = {}) {
			// verify required parameter 'pushSubscriptionDto' is not null or undefined
			assertParamExists("saveSubscription", "pushSubscriptionDto", body);

			const localVarPath = `/api/subscriptions`;
			// use dummy base URL string because the URL constructor only accepts absolute URLs.
			const requestUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
			let baseOptions;
			if (this.configuration) {
				baseOptions = this.configuration.baseOptions;
			}

			const axiosRequestConfig: AxiosRequestConfig = { method: "POST", ...baseOptions, ...options };
			const requestHeaderParameter = {} as any;
			const requestQueryParameter = {} as any;

			requestHeaderParameter["Content-Type"] = "application/json";

			setSearchParams(requestUrlObj, requestQueryParameter);
			let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
			axiosRequestConfig.headers = { ...requestHeaderParameter, ...headersFromBaseOptions, ...options.headers };
			axiosRequestConfig.data = serializeDataIfNeeded(body, axiosRequestConfig, this.configuration);

			axiosRequestConfig["url"] = toPathString(requestUrlObj);
			axiosRequestConfig["baseURL"] = this.configuration.basePath;

			return this.axios.request<SubscriptionResponseDto>(axiosRequestConfig);
		}
	}
}
