name: Deploy to TEST

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-master.yml'
      - 'Dockerfile'
      - '.dockerignore'
      - 'backend/**'
      - 'frontend/**'

jobs:
  build:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the updated source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push it to DockerHub
        uses: docker/build-push-action@v6
        with:
          build-args: NG_CONFIGURATION=production
          push: true
          context: .
          tags: "ghcr.io/smallhillcz/svatba:test"
          cache-from: type=gha,scope=test
          cache-to: type=gha,mode=max,scope=test

  deploy:
    name: Notify Watchtower
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Tell the watchtower server there is a new image
        env:
          WATCHTOWER_URL: ${{ vars.WATCHTOWER_URL }}
          WATCHTOWER_TOKEN: ${{ secrets.WATCHTOWER_TOKEN }}
        run: 'curl -I -H "Authorization: Bearer $WATCHTOWER_TOKEN" $WATCHTOWER_URL'
